#!/bin/bash

echo Destroying Vault ...
sudo podman stop vault && sudo podman rm vault
sudo podman volume rm vault-config
sudo podman volume rm vault-data
sudo podman volume rm vault-logs
sudo podman volume rm vault-policies
